# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2025-2026 Giacomo Battaglia
"""Shell completion scripts for leph and libephemeris CLIs.

Provides `leph completion {zsh,bash,fish}` commands that output custom
completion scripts. Unlike Click's built-in completion, these scripts:

  1. Auto-create a ``leph`` shell function for this source checkout
  2. Pin the project path so the function works outside the repository
  3. Work whether the venv is activated or not

Provenance:
    Project-authored shell-completion text generation. It contains no
    astronomical model, scientific datum, or numerical coefficient.
"""

from __future__ import annotations

import shlex
from pathlib import Path

import click

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_LEPH_COMMAND = (
    f"uv run --project {shlex.quote(str(_PROJECT_ROOT))} python -m libephemeris.dev_cli"
)

# ---------------------------------------------------------------------------
# Completion scripts — custom, uv-aware
# ---------------------------------------------------------------------------

_ZSH_SCRIPT = r"""# --- leph shell integration (zsh) ---
# Generated by: leph completion zsh
# Add to ~/.zshrc:  eval "$(uv run ./leph completion zsh)"
# Or:  uv run ./leph completion zsh > ~/.leph-completion.zsh
#      echo 'source ~/.leph-completion.zsh' >> ~/.zshrc

# Make 'leph' available from any directory using this checkout.
leph() { command __LEPH_COMMAND__ "$@"; }

# Initialize zsh's completion system only when the current shell has not
# already done so.  This keeps repeated sourcing idempotent while making the
# generated quick-start script work in a pristine zsh session.
if ! (( $+functions[compdef] )); then
    autoload -Uz compinit
    compinit
fi

_leph_completion() {
    local -a completions completions_with_descriptions response

    response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) _LEPH_COMPLETE=zsh_complete __LEPH_COMMAND__)}")

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi
    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

compdef _leph_completion leph
"""

_BASH_SCRIPT = r"""# --- leph shell integration (bash) ---
# Generated by: leph completion bash
# Add to ~/.bashrc:  eval "$(uv run ./leph completion bash)"
# Or:  uv run ./leph completion bash > ~/.leph-completion.bash
#      echo 'source ~/.leph-completion.bash' >> ~/.bashrc

# Make 'leph' available from any directory using this checkout.
leph() { command __LEPH_COMMAND__ "$@"; }

_leph_completion() {
    local IFS=$'\n'
    local response

    response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD \
        _LEPH_COMPLETE=bash_complete __LEPH_COMMAND__)

    COMPREPLY=()
    for completion in $response; do
        IFS=',' read -r type value <<< "$completion"

        if [[ $type == 'dir' ]]; then
            COMPREPLY=()
            compopt -o dirnames
        elif [[ $type == 'file' ]]; then
            COMPREPLY=()
            compopt -o default
        elif [[ $type == 'plain' ]]; then
            COMPREPLY+=("$value")
        fi
    done
    return 0
}

complete -o default -F _leph_completion leph
"""

_FISH_SCRIPT = r"""# --- leph shell integration (fish) ---
# Generated by: leph completion fish
# Add to ~/.config/fish/conf.d/leph.fish:
#   uv run ./leph completion fish > ~/.config/fish/conf.d/leph.fish

function leph
    command __LEPH_COMMAND__ $argv
end

function _leph_completion
    set -l response
    set response (env _LEPH_COMPLETE=fish_complete COMP_WORDS=(commandline -cp) \
        COMP_CWORD=(commandline -t) __LEPH_COMMAND__)
    for completion in $response
        set -l metadata (string split "," $completion)
        if test $metadata[1] = "dir"
            __fish_complete_directories $metadata[2]
        else if test $metadata[1] = "file"
            __fish_complete_path $metadata[2]
        else if test $metadata[1] = "plain"
            echo $metadata[2]
        end
    end
end

complete -c leph -f -a "(_leph_completion)"
"""

_SCRIPTS = {
    "zsh": _ZSH_SCRIPT,
    "bash": _BASH_SCRIPT,
    "fish": _FISH_SCRIPT,
}


def _render_script(shell: str) -> str:
    """Render a completion script pinned to this source checkout."""
    return _SCRIPTS[shell].replace("__LEPH_COMMAND__", _LEPH_COMMAND)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@click.group(
    "completion",
    short_help="Generate shell completion scripts (zsh, bash, fish).",
    help="Generate shell completion scripts for leph.\n\n"
    "These scripts make TAB completion work and also create a 'leph' shell\n"
    "function so you can type 'leph' directly without activating the venv.\n\n"
    "Quick setup (zsh):\n\n"
    '  eval "$(uv run ./leph completion zsh)"     # Test it now\n'
    "  uv run ./leph completion zsh >> ~/.zshrc    # Make it permanent\n\n"
    "After reloading your shell:\n\n"
    "  leph <TAB>               # Shows: test, code, leb, download, ...\n"
    "  leph test <TAB>          # Shows: skyfield, leb-backend, leb-format, ...\n"
    "  leph test skyfield <TAB> # Shows: essential, smoke, unit, ...",
)
def completion_group() -> None:
    """Shell completion generation."""


@completion_group.command(
    short_help="Print zsh completion script (for ~/.zshrc).",
)
def zsh() -> None:
    """Print zsh completion + shell function script.

    \b
    Quick test:
      eval "$(uv run ./leph completion zsh)"
    \b
    Permanent setup (pick one):
      # Option A: append to .zshrc
      uv run ./leph completion zsh >> ~/.zshrc
    \b
      # Option B: separate file
      uv run ./leph completion zsh > ~/.leph-completion.zsh
      echo 'source ~/.leph-completion.zsh' >> ~/.zshrc
    \b
    Then reload:
      source ~/.zshrc
    """
    click.echo(_render_script("zsh"))


@completion_group.command(
    short_help="Print bash completion script (for ~/.bashrc).",
)
def bash() -> None:
    """Print bash completion + shell function script.

    \b
    Quick test:
      eval "$(uv run ./leph completion bash)"
    \b
    Permanent setup:
      uv run ./leph completion bash >> ~/.bashrc
      source ~/.bashrc
    """
    click.echo(_render_script("bash"))


@completion_group.command(
    short_help="Print fish completion script (for conf.d/).",
)
def fish() -> None:
    """Print fish completion + shell function script.

    \b
    Setup:
      uv run ./leph completion fish > ~/.config/fish/conf.d/leph.fish
    """
    click.echo(_render_script("fish"))
