# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2025-2026 Giacomo Battaglia
"""Shared defining data for predefined sidereal modes.

Provenance:
    This is a generated scientific artifact. Its sole authoritative generator
    is ``scripts/generate_ayanamsha_definitions.py``; every emitted entry maps
    to the exact source/status row in ``docs/reference/ayanamsha.md``.
    Published and geometric definitions remain distinct from rows labelled
    Secondary or Convention. No zero point is fitted to compatibility output.
    Regeneration preserves this evidence boundary.

AUTO-GENERATED by scripts/generate_ayanamsha_definitions.py - edit that
script, not this module. Every entry carries a concise source description; its
full evidence status and derivation conventions are documented in the
generator and in docs/reference/ayanamsha.md. No value is fitted to another
ephemeris implementation's output.

Runtime model for epoch modes (identical to the ``SIDM_USER`` contract):

    ayanamsha(t) = value + method_b_accumulated_precession(t, epoch)

with the Vondrak, Capitaine & Wallace (2011) Method-B accumulation on the
mean ecliptic of the defining epoch. Dynamic star and galactic modes are
evaluated from live catalog geometry in planets.py against the published
target longitudes below.
"""

from __future__ import annotations

# mode: (ayanamsha at defining epoch [deg], defining epoch [TT JD])
AYANAMSHA_DEFINING: dict[int, tuple[float, float]] = {
    # FAGAN_BRADLEY: Fagan & Firebrace, Primer of Sidereal Astrology: SVP 335°57'28.64" at B1950.0
    0: (24.042044444444457, 2433282.42345905),
    # LAHIRI: Indian Astronomical Ephemeris (Positional Astronomy Centre, Kolkata): ayanamsa 23°51'25".53 at 2000 Jan 1.5 TT (J2000.0)
    1: (23.85709166666667, 2451545.0),
    # DELUCE: De Luce, Constellational Astrology (1963) p.5: 26°24'47" in 1900
    2: (26.413055555555555, 2415020.31352),
    # RAMAN: Raman, Hindu Predictive Astrology App. A: (year-397) x 50 1/3", anchored at 1900.0
    3: (21.014166666666668, 2415020.0),
    # USHASHASHI: Usha & Shashi, "Hindu Astrological Calculations" (Sagar,
    # 1978) — the mode's attributed publication. Zero epoch 559 CE is the
    # value stated by that tradition; the primary page transcription is
    # still pending acquisition (value corroborated only against secondary
    # compilations, never fitted to external output).
    4: (0.0, 1925312.0),
    # KRISHNAMURTI: K. S. Krishnamurti, "Krishnamurti Padhdhati" (the K.P.
    # Reader series, Madras, 1960s): the K.P. ayanamsha is 22°21'50" at 1900
    # January 0.5; volume/page transcription pending.
    5: (22.36388888888889, 2415020.0),
    # DJWHAL_KHUL: Bailey/Ageless Wisdom: Aquarian age (ayanamsha 30°) begins 2117
    6: (30.0, 2494279.0),
    # YUKTESHWAR: Sri Yukteswar, The Holy Science (1894): 20°54'36" at the spring 1894 equinox
    7: (20.91, 2412908.1187773715),
    # JN_BHASIN: J.N. Bhasin (published Hindu-astrology author, e.g.
    # "Sidereal Astrology") — attributed originator. Zero epoch 364 CE per
    # the circulating tradition; primary page transcription pending
    # (corroborated against secondary compilations only, never fitted).
    8: (0.0, 1854089.0),
    # BABYL_KUGLER1: F.X. Kugler, "Sternkunde und Sterndienst in Babel" II,
    # solution 1. Zero epoch 309 CE as tabulated in the scholarly secondary
    # literature on the Babylonian zodiac norms (B.L. van der Waerden,
    # "History of the Zodiac", Archiv fuer Orientforschung 16, 1953,
    # 216-230; cf. Huber, Centaurus 5, 1958); Kugler primary transcription
    # pending.
    9: (0.0, 1834000.0),
    # BABYL_KUGLER2: Kugler, Sternkunde II, solution 2. Zero epoch 208 CE
    # per the van der Waerden (1953) / Huber (1958) tabulation of the
    # Babylonian norms; Kugler primary transcription pending.
    10: (0.0, 1797110.0),
    # BABYL_KUGLER3: Kugler, Sternkunde II, solution 3. Zero epoch 146 CE
    # per the van der Waerden (1953) / Huber (1958) tabulation of the
    # Babylonian norms; Kugler primary transcription pending.
    11: (0.0, 1774464.0),
    # BABYL_HUBER: P. Huber, "Über den Nullpunkt der babylonischen Ekliptik",
    # Centaurus 5 (1958), pp. 192-208: the vernal point stood at Babylonian
    # Aries 4°28' in -100, i.e. ayanamsha -4°28' at that epoch.
    12: (-4.466666666666667, 1684613.0),
    # BABYL_ETPSC: eta Piscium Babylonian norm as discussed by R. Mercier
    # ("Studies in the Medieval Conception of Precession"); zero epoch
    # 237 CE per that secondary tabulation; primary transcription pending.
    13: (0.0, 1807702.0),
    # HIPPARCHOS: Mercier, Studies in the Medieval Conception of Precession: Hipparchan norm zero 545 CE
    15: (0.0, 1920199.0),
    # SASSANIAN: Mercier: Sassanian (Zij-i Shah) zero epoch 18 March 564 CE
    16: (0.0, 1927136.0),
    # J2000: Mean ecliptic/equinox of J2000 (frame epoch)
    18: (0.0, 2451545.0),
    # J1900: Mean ecliptic/equinox of 1900 January 0.5 (frame epoch)
    19: (0.0, 2415020.0),
    # B1950: Mean ecliptic/equinox of B1950.0 (frame epoch)
    20: (0.0, 2433282.42345905),
    # SURYASIDDHANTA: Surya Siddhanta (Burgess): zero at the Kali-3600 equinox, 21 March 499 CE
    21: (0.0, 1903395.1338202194),
    # SURYASIDDHANTA_MSUN: Surya Siddhanta mean Sun (Burgess): mean Sun at the sidereal zero, Ardharatrika Kali epoch (Ujjayini midnight) + 3600 SS years
    22: (-0.21510829031467438, 1903396.8775657457),
    # ARYABHATA: Aryabhatiya (Clark): zero at the Kali-3600 equinox, 21 March 499 CE
    23: (0.0, 1903395.1338202194),
    # ARYABHATA_MSUN: Aryabhatiya mean Sun (Clark): mean Sun at the sidereal zero, Audayika Kali epoch (Ujjayini sunrise) + 3600 Aryabhata years
    24: (-0.23810671619139612, 1903396.8542324193),
    # SS_REVATI: Surya Siddhanta VIII: Revati (zeta Psc) at polar longitude 359°50' at the Kali-3600 epoch
    25: (-0.7922573227712064, 1903395.1338202194),
    # SS_CITRA: Surya Siddhanta VIII: Citra (Spica) at polar longitude 180° at the Kali-3600 epoch
    26: (2.1105983371992068, 1903395.1338202194),
    # ARYABHATA_522: Aryabhata 522 CE tradition: zero at the 522 CE spring equinox
    37: (0.0, 1911798.0),
    # BABYL_BRITTON: J.P. Britton, "Studies in Babylonian lunar theory,
    # Part III" (Archive for History of Exact Sciences 64, 2010): the
    # uniform-zodiac displacement Delta-lambda* = 3.20 deg - 1.3828 deg/cy
    # * Y. The zero epoch is DERIVED from that published formula:
    # Y = 3.20/1.3828 = 2.314 centuries after the common-era origin,
    # i.e. ~231 CE (rounded 230 CE here). Not a transcription gap: the
    # epoch follows arithmetically from Britton's printed constants.
    38: (0.0, 1805145.0),
    # GALEQU_FIORENZA: Fiorenza: galactic-equator ayanamsha 25° at 2000-01-01
    41: (25.0, 2451544.5),
    # LAHIRI_1940: the early N.C. Lahiri tradition (Indian Ephemeris, 1st
    # ed.). Zero epoch ~285/286 CE is the Chitrapaksha coincidence year
    # discussed in the Report of the Calendar Reform Committee (CSIR, New
    # Delhi, 1955); first-edition page transcription pending.
    43: (0.0, 1825599.0),
    # LAHIRI_VP285: Vernal-point convention: zero at the 285 CE spring equinox
    44: (0.0, 1825233.3060523525),
    # KRISHNAMURTI_VP291: Vernal-point convention: zero at the 291 CE spring equinox
    45: (0.0, 1827424.7590899938),
    # LAHIRI_ICRC: Calendar Reform Committee (1955): true ayanamsha 23°15' at 1956-03-21 00:00 ET, stored as mean (- dpsi at the epoch)
    46: (23.245339462821466, 2435553.5),
}

# Modes evaluated from live catalog/frame geometry in planets.py.
DYNAMIC_AYANAMSHA_MODES = frozenset(
    {14, 17, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 40, 42}
)

# Galactic-center modes: published sidereal target longitude of Sgr A*.
GALCENT_TARGET_LON: dict[int, float] = {
    # Galactic Center at 0° Sagittarius
    17: 240.0,
    # Gil Brand, Himmlische Matrix: GC at the double golden section of
    # Sagittarius, 240° + 30°/phi^4 with phi = (1 + sqrt 5)/2; the literal is
    # that expression evaluated in double precision (exact to the last digit).
    30: 244.37694101250946,
    # Cochrane: Galactic Center at 0° Capricorn
    40: 270.0,
}

# Wilhelm: Sgr A* hour-circle (dhruva) projection at the middle of Mula
# (246°40').
MULA_WILHELM_TARGET_LON = 246.66666666666666

# Aldebaran at 15° Taurus (45° absolute): the star-fixed anchor of the
# "Aldebaran = 15 Tau" sidereal convention, the Babylonian exaltation-degree
# tradition revived by Cyril Fagan, "Zodiacs Old and New" (Llewellyn, 1950).
# It defines sidereal mode SIDM_ALDEBARAN_15TAU (14) and is distinct from the
# Fagan-Bradley SVP ayanamsha, from which it differs by ~1'.
ALDEBARAN_TARGET_LON = 45.0

# Sheoran, The Science of Time (2017): the sidereal zero is anchored
# to the live star Asellus Australis (delta Cancri) held at the fixed
# sidereal longitude 103°29'32.9375", chosen so that the Sun stands at
# sidereal 330° (Pisces 0) at the 4174 BCE winter solstice; the star
# anchor makes "the actual rate of precession irrelevant" (the
# 1°/71.75 yr rule is the author's stated approximation only). It
# defines sidereal mode SIDM_TRUE_SHEORAN (39).
SHEORAN_TARGET_LON = 103.49248263888889

# Mardyks, Sacred Astronomy (1991): ayanamsha exactly 30° at
# the September equinox 1998 (Meeus mean-equinox instant); fixed-epoch
# frame mode propagated with the IAU 2006 general-precession angle.
MARDYKS_DEFINING: tuple[float, float] = (30.0, 2451079.733114197)

# Vettius Valens lunar-epoch mode (SIDM_VALENS_MOON, 42): defining pair.
# The ayanamsha is VALENS_MOON_AYAN_T0_DEG plus the Method-B precession
# accumulated from the defining UT epoch (see planets._calc_ayanamsa), the
# same formula every other epoch pair uses. The epoch (JD 1775845.5 UT, about
# 150 CE) and the offset (-2.9422 deg) are compatibility values, primary
# source not verified: no transcription of Valens' Anthologiae backs them and
# no derivation from it is claimed. Convention of this library.
VALENS_MOON_T0_UT = 1775845.5
VALENS_MOON_AYAN_T0_DEG = -2.9422
