# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025-2026 Giacomo Battaglia
"""Shared defining data for predefined sidereal modes.

AUTO-GENERATED by scripts/generate_ayanamsha_definitions.py - edit that
script, not this module. Every entry derives from the published defining
statement cited on its line; the derivation conventions are documented in
the generator and in docs/reference/ayanamsha.md. No value is fitted to any
external ephemeris implementation.

Runtime model for epoch modes (identical to the ``SIDM_USER`` contract):

    ayanamsha(t) = value + method_b_accumulated_precession(t, epoch)

with the Vondrak, Capitaine & Wallace (2011) Method-B accumulation on the
mean ecliptic of the defining epoch. Dynamic star and galactic modes are
evaluated from live catalog geometry in planets.py against the published
target longitudes below.
"""

from __future__ import annotations

# mode: (ayanamsha at defining epoch [deg], defining epoch [TT JD])
AYANAMSHA_DEFINING: dict[int, tuple[float, float]] = {
    # FAGAN_BRADLEY: Fagan & Firebrace, Primer of Sidereal Astrology: SVP 335°57'28.64" at B1950.0
    0: (24.042044444444457, 2433282.42345905),
    # LAHIRI: Indian Astronomical Ephemeris: 23°15'00".658 at 1956-03-21 00:00 ET
    1: (23.250182777777777, 2435553.5),
    # DELUCE: De Luce, Constellational Astrology (1963) p.5: 26°24'47" in 1900
    2: (26.413055555555555, 2415020.31352),
    # RAMAN: Raman, Hindu Predictive Astrology App. A: (year-397) x 50 1/3", anchored at 1900.0
    3: (21.014166666666668, 2415020.0),
    # USHASHASHI: Usha & Shashi (1978); traditional zero epoch 559 CE (primary transcription pending)
    4: (0.0, 1925312.0),
    # KRISHNAMURTI: Krishnamurti Paddhati: 22°21'50" at 1900 January 0.5
    5: (22.36388888888889, 2415020.0),
    # DJWHAL_KHUL: Bailey/Ageless Wisdom: Aquarian age (ayanamsha 30°) begins 2117
    6: (30.0, 2494279.0),
    # YUKTESHWAR: Sri Yukteswar, The Holy Science (1894): 20°54'36" at the spring 1894 equinox
    7: (20.91, 2412908.1187773715),
    # JN_BHASIN: J.N. Bhasin; traditional zero epoch 364 CE (primary transcription pending)
    8: (0.0, 1854089.0),
    # BABYL_KUGLER1: Kugler, Sternkunde II, solution 1; zero epoch 309 CE (primary transcription pending)
    9: (0.0, 1834000.0),
    # BABYL_KUGLER2: Kugler, Sternkunde II, solution 2; zero epoch 208 CE (primary transcription pending)
    10: (0.0, 1797110.0),
    # BABYL_KUGLER3: Kugler, Sternkunde II, solution 3; zero epoch 146 CE (primary transcription pending)
    11: (0.0, 1774464.0),
    # BABYL_HUBER: Huber, Centaurus 5 (1958): vernal point at Babylonian Aries 4°28' in -100
    12: (-4.466666666666667, 1684613.0),
    # BABYL_ETPSC: eta Piscium Babylonian norm (Mercier); zero epoch 237 CE (primary transcription pending)
    13: (0.0, 1807702.0),
    # HIPPARCHOS: Mercier, Studies in the Medieval Conception of Precession: Hipparchan norm zero 545 CE
    15: (0.0, 1920199.0),
    # SASSANIAN: Mercier: Sassanian (Zij-i Shah) zero epoch 18 March 564 CE
    16: (0.0, 1927136.0),
    # J2000: Mean ecliptic/equinox of J2000 (frame epoch)
    18: (0.0, 2451545.0),
    # J1900: Mean ecliptic/equinox of 1900 January 0.5 (frame epoch)
    19: (0.0, 2415020.0),
    # B1950: Mean ecliptic/equinox of B1950.0 (frame epoch)
    20: (0.0, 2433282.42345905),
    # SURYASIDDHANTA: Surya Siddhanta (Burgess): zero at the Kali-3600 equinox, 21 March 499 CE
    21: (0.0, 1903395.1338202194),
    # SURYASIDDHANTA_MSUN: Surya Siddhanta mean Sun: Ardharatrika Kali epoch JD 588465.75 + 3600 SS years (Burgess)
    22: (0.0, 1903397.2733333334),
    # ARYABHATA: Aryabhatiya (Clark): zero at the Kali-3600 equinox, 21 March 499 CE
    23: (0.0, 1903395.1338202194),
    # ARYABHATA_MSUN: Aryabhatiya mean Sun: Audayika Kali epoch JD 588466.0 + 3600 Aryabhata years (Clark)
    24: (0.0, 1903397.25),
    # SS_REVATI: Surya Siddhanta VIII: Revati (zeta Psc) at polar longitude 359°50' at the Kali-3600 epoch
    25: (-0.7922573227712064, 1903395.1338202194),
    # SS_CITRA: Surya Siddhanta VIII: Citra (Spica) at polar longitude 180° at the Kali-3600 epoch
    26: (2.1105983371992068, 1903395.1338202194),
    # ARYABHATA_522: Aryabhata 522 CE tradition: zero at the 522 CE spring equinox
    37: (0.0, 1911798.0),
    # BABYL_BRITTON: Britton, AHES 64 (2010) uniform zodiac; zero epoch 230 CE (primary transcription pending)
    38: (0.0, 1805145.0),
    # TRUE_SHEORAN: Sunil Sheoran, The Science of Time: ayanamsha -60° at the winter solstice 4174 BCE
    39: (-60.0, 197256.37679305955),
    # GALEQU_FIORENZA: Fiorenza: galactic-equator ayanamsha 25° at 2000-01-01
    41: (25.0, 2451544.5),
    # LAHIRI_1940: Lahiri (1940) tradition; zero epoch 286 CE (primary transcription pending)
    43: (0.0, 1825599.0),
    # LAHIRI_VP285: Vernal-point convention: zero at the 285 CE spring equinox
    44: (0.0, 1825233.3060523525),
    # KRISHNAMURTI_VP291: Vernal-point convention: zero at the 291 CE spring equinox
    45: (0.0, 1827424.7590899938),
    # LAHIRI_ICRC: Calendar Reform Committee (1955): 23°15' at 1956-03-21 00:00 ET
    46: (23.25, 2435553.5),
}

# Modes evaluated from live catalog/frame geometry in planets.py.
DYNAMIC_AYANAMSHA_MODES = frozenset(
    {14, 17, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 40, 42}
)

# Galactic-center modes: published sidereal target longitude of Sgr A*.
GALCENT_TARGET_LON: dict[int, float] = {
    # Galactic Center at 0° Sagittarius
    17: 240.0,
    # Gil Brand, Himmlische Matrix: GC at the double golden section of Sagittarius, 240° + 30°/phi^4
    30: 244.37694101250946,
    # Cochrane: Galactic Center at 0° Capricorn
    40: 270.0,
}

# Wilhelm: Sgr A* hour-circle (dhruva) projection at the middle of Mula
# (246°40').
MULA_WILHELM_TARGET_LON = 246.66666666666666

# Aldebaran at 15° Taurus: published target longitude.
ALDEBARAN_TARGET_LON = 45.0

# Mardyks, Sacred Astronomy (1991): ayanamsha exactly 30° at
# the September equinox 1998 (Meeus mean-equinox instant); fixed-epoch
# frame mode propagated with the IAU 2006 general-precession angle.
MARDYKS_DEFINING: tuple[float, float] = (30.0, 2451079.733114197)

# Vettius Valens lunar-epoch mode: defining UT epoch and offset.
# Offset consistent with the ~-3 deg Hellenistic sidereal norm reported
# in the scholarship (e.g. GRBS 56 (2016) 573-575 discussion of Valens'
# longitudes); primary transcription of Anthologiae I.18 pending.
VALENS_MOON_T0_UT = 1775845.5
VALENS_MOON_AYAN_T0_DEG = -2.9422
